apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: location-consumer-api
  name: location-consumer-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: location-consumer-api
  template:
    metadata:
      labels:
        app: location-consumer-api
    spec:
      containers:
      - name: udaconnect-location-consumer-api
        image: hngiap94/udaconnect-location-consumer-api:latest
        imagePullPolicy: Always
        env:
        - name: KAFKA_TOPIC
          valueFrom:
            configMapKeyRef:
              name: kafka-configmap
              key: KAFKA_TOPIC
        - name: KAFKA_SERVER
          valueFrom:
            configMapKeyRef:
              name: kafka-configmap
              key: KAFKA_SERVER
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: location-db-configmap
              key: DB_NAME
        - name: DB_USERNAME
          valueFrom:
            configMapKeyRef:
              name: location-db-configmap
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: location-db-secret
              key: DB_PASSWORD
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: location-db-configmap
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: location-db-configmap
              key: DB_PORT
        - name: PYTHONUNBUFFERED
          value: '0'
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: location-consumer-api
  name: location-consumer-api-service
spec:
  ports:
  - name: location-consumer-api-service-port
    port: 9092
    targetPort: 9092
  selector:
    app: location-consumer-api
  type: NodePort